#!/bin/sh

if [ -r /etc/default/gpio-heartbeat ]; then
    . /etc/default/gpio-heartbeat
fi

gpio=${GPIOHEARTBEAT=20}

[ ! -w /sys/class/gpio/gpio${gpio}/direction ] && echo $gpio > /sys/class/gpio/export

sys=/sys/class/gpio/gpio${gpio}
dir=${sys}/direction
val=${sys}/value
echo out > $dir

while true; do
    VAL=`cat /sys/class/gpio/gpio${gpio}/value`
    echo $((VAL^=1)) > $val
    sleep 1
done
